prometheus:

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - default-pool

  ingress:
    enabled: true
    hostname: pro.sys.sysf.one
    tls: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod

  persistence:
    enabled: true
    size: 16Gi
    storageClass: "ceph-filesystem"
    accessModes:
      - ReadWriteMany

  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
        - job_name: 'rook-ceph--rook-ceph-mgr'
          static_configs:
            - targets: ['rook-ceph-mgr.rook-ceph.svc.cluster.local:9283']
        - job_name: 'admin--nginx-ingress-controller-metrics'
          static_configs:
            - targets: ['nginx-ingress-controller-metrics.admin.svc.cluster.local:9913']
        - job_name: 'admin--grafana'
          static_configs:
            - targets: ['grafana.admin.svc.cluster.local:3000']
        - job_name: 'admin--keycloak-metrics'
          static_configs:
            - targets: ['keycloak-metrics.admin.svc.cluster.local:9990']

operator:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - default-pool

alertmanager:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - default-pool
