prometheus:

  ingress:
    enabled: true
    hostname: pro.sys.sysf.one
    tls: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-url: "https://oauth.sys.sysf.one/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://oauth.sys.sysf.one/oauth2/start?rd=$scheme://$best_http_host$request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
      acme.cert-manager.io/http01-edit-in-place: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.org/proxy-buffer-size: "16k"

  persistence:
    enabled: true
    size: 32Gi
    accessModes:
      - ReadWriteMany

  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
        - job_name: 'rook-ceph--rook-ceph-mgr'
          static_configs:
            - targets: ['rook-ceph-mgr.rook-ceph.svc.cluster.local:9283']
        - job_name: 'gitlab'
          static_configs:
            - targets: ['gitlab-nginx-ingress-controller-metrics.gitlab.svc.cluster.local:10254']
            # - targets: ['gitlab-postgresql-metrics.gitlab.svc.cluster.local:9187']
            - targets: ['gitlab-redis-metrics.gitlab.svc.cluster.local:9121']
            - targets: ['gitlab-webservice-default.gitlab.svc.cluster.local:8083']
            - targets: ['gitlab-gitaly.gitlab.svc.cluster.local:9236']
            - targets: ['gitlab-gitlab-exporter.gitlab.svc.cluster.local:9168']
            - targets: ['gitlab-kas.gitlab.svc.cluster.local:8151']
        - job_name: 'gitlab-runner'
          static_configs:
            - targets: ['gitlab-runner-docker.gitlab-runner.svc.cluster.local:9252']
            - targets: ['gitlab-runner-kubernetes.gitlab-runner.svc.cluster.local:9252']

coreDns:
  enabled: false
