prometheus:

  ingress:
    enabled: true
    hostname: pro.sys.sysf.one
    tls: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: tls-sys

  persistence:
    enabled: true
    size: 16Gi
    storageClass: "ceph-filesystem"
    accessModes:
      - ReadWriteMany

  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
        - job_name: 'rook-ceph--rook-ceph-mgr'
          static_configs:
            - targets: ['rook-ceph-mgr.rook-ceph.svc.cluster.local:9283']
        - job_name: 'admin--nginx-ingress-controller-metrics'
          static_configs:
            - targets: ['nginx-ingress-controller-metrics.admin.svc.cluster.local:9913']
        - job_name: 'admin--elasticsearch-metrics'
          static_configs:
            - targets: ['elasticsearch-metrics.admin.svc.cluster.local:9114']
        - job_name: 'admin--grafana'
          static_configs:
            - targets: ['grafana.admin.svc.cluster.local:3000']
        - job_name: 'admin--keycloak-metrics'
          static_configs:
            - targets: ['keycloak-metrics.admin.svc.cluster.local:9990']
