stages:
  - deploy

before_script:
  - env
  - uname -a

env-admin:
  stage: deploy
  image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.1.0"
  environment: admin
  script:
    - gl-helmfile --environment admin apply --suppress-secrets

# env-prd:
#  stage: deploy
#  image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.1.0"
#  environment: prd
#  script:
#    - gl-ensure-namespace env-prd
#    - kubectl config set-context --current --namespace=env-prd
#    - "kubectl get secret ssh-config --namespace=default -o yaml | sed 's/namespace: default/namespace: env-prd/' | kubectl apply --namespace=env-prd -f - || true"
#    - "kubectl get secret tls-sys --namespace=default -o yaml | sed 's/namespace: default/namespace: env-prd/' | kubectl apply --namespace=env-prd -f - || true"
#    - "kubectl get secret mariadb --namespace=default -o yaml | sed 's/namespace: default/namespace: env-prd/' | kubectl apply --namespace=env-prd -f - || true"
#    - gl-helmfile --environment prd apply --suppress-secrets

# env-stg:
#  stage: deploy
#  image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.1.0"
#  environment: stg
#  script:
#    - gl-ensure-namespace env-stg
#    - kubectl config set-context --current --namespace=env-stg
#    - "kubectl get secret ssh-config --namespace=default -o yaml | sed 's/namespace: default/namespace: env-stg/' | kubectl apply --namespace=env-stg -f - || true"
#    - "kubectl get secret tls-sys --namespace=default -o yaml | sed 's/namespace: default/namespace: env-stg/' | kubectl apply --namespace=env-stg -f - || true"
#    - "kubectl get secret mariadb --namespace=default -o yaml | sed 's/namespace: default/namespace: env-stg/' | kubectl apply --namespace=env-stg -f - || true"
#    - gl-helmfile --environment stg apply --suppress-secrets

# env-dev:
#  stage: deploy
#  image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.1.0"
#  environment: dev
#  script:
#    - gl-ensure-namespace env-dev
#    - kubectl config set-context --current --namespace=env-dev
#    - "kubectl get secret ssh-config --namespace=default -o yaml | sed 's/namespace: default/namespace: env-dev/' | kubectl apply --namespace=env-dev -f - || true"
#    - "kubectl get secret tls-sys --namespace=default -o yaml | sed 's/namespace: default/namespace: env-dev/' | kubectl apply --namespace=env-dev -f - || true"
#    - "kubectl get secret mariadb --namespace=default -o yaml | sed 's/namespace: default/namespace: env-dev/' | kubectl apply --namespace=env-dev -f - || true"
#    - gl-helmfile --environment dev apply --suppress-secrets

# env-ide1:
#  stage: deploy
#  image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.1.0"
#  environment: ide1
#  script:
#    - export SYS_HELM_NAMESPACE_SUFFIX=ide1
#    - gl-ensure-namespace env-ide1
#    - kubectl config set-context --current --namespace=env-ide1
#    - "kubectl get secret ssh-config --namespace=default -o yaml | sed 's/namespace: default/namespace: env-ide1/' | kubectl apply --namespace=env-ide1 -f - || true"
#    - "kubectl get secret tls-sys --namespace=default -o yaml | sed 's/namespace: default/namespace: env-ide1/' | kubectl apply --namespace=env-ide1 -f - || true"
#    - "kubectl get secret mariadb --namespace=default -o yaml | sed 's/namespace: default/namespace: env-ide1/' | kubectl apply --namespace=env-ide1 -f - || true"
#    - gl-helmfile --environment ide apply --suppress-secrets
