stages:
  - deploy

before_script:
  - env
  - uname -a
  - kubectl config use-context kubernetes/cluster/sysf:sysf1

admin:
  stage: deploy
  image:
    name: registry.gitlab.sysf.one/docker/image/helmfile:latest
    entrypoint: [""]
  environment: admin
  tags:
    - kubernetes
  script:
    - helmfile --environment admin apply --suppress-secrets

# gitlab:
#   stage: deploy
#   image:
#     name: registry.gitlab.sysf.one/docker/image/helmfile:latest
#     entrypoint: [""]
#   environment: gitlab
#   tags:
#     - kubernetes
#   script:
#     - helmfile --environment gitlab apply --suppress-secrets

# gitlab-runner:
#   stage: deploy
#   image:
#     name: registry.gitlab.sysf.one/docker/image/helmfile:latest
#     entrypoint: [""]
#   environment: gitlab-runner
#   tags:
#     - kubernetes
#   script:
#     - helmfile --file applications/gitlab-runner/helmfile.yaml --environment gitlab-runner apply --suppress-secrets

ops:
  stage: deploy
  image:
    name: registry.gitlab.sysf.one/docker/image/helmfile:latest
    entrypoint: [""]
  environment: ops
  tags:
    - kubernetes
  script:
    - kubectl create namespace ops || true
    - kubectl label --overwrite ns ops namespace-node-affinity=enabled
    - helmfile --environment ops apply --suppress-secrets


# env-prd:
#  stage: deploy
#  image:
#     name: registry.gitlab.sysf.one/docker/image/helmfile:latest
#     entrypoint: [""]
#  environment: prd
#  tags:
#     - kubernetes
#  script:
#    - export SYS_HELM_NEW="false"
#    - kubectl create namespace env-prd || true
#    - kubectl label --overwrite ns env-prd env=true
#    - kubectl label --overwrite ns env-prd namespace-node-affinity=enabled
#    - kubectl config set-context --current --namespace=env-prd
#    - "kubectl get secret sys-env-var-config-prd --namespace=default -o yaml | sed 's/namespace: default/namespace: env-prd/' | sed 's/name: sys-env-var-config-prd/name: sys-env-var-config/' | kubectl apply --namespace=env-prd -f - || true"
#    - helmfile --file applications/env/helmfile.yaml --environment prd apply --suppress-secrets

# env-stg:
#  stage: deploy
#  image:
#     name: registry.gitlab.sysf.one/docker/image/helmfile:latest
#     entrypoint: [""]
#  environment: stg
#  tags:
#     - kubernetes
#  script:
#    - export SYS_HELM_NEW="false"
#    - kubectl create namespace env-ide1 || true
#    - kubectl label --overwrite ns env-stg env=true
#    - kubectl label --overwrite ns env-stg namespace-node-affinity=enabled
#    - kubectl config set-context --current --namespace=env-stg
#    - "kubectl get secret sys-env-var-config-stg --namespace=default -o yaml | sed 's/namespace: default/namespace: env-stg/' | sed 's/name: sys-env-var-config-stg/name: sys-env-var-config/' | kubectl apply --namespace=env-stg -f - || true"
#    - helmfile --file applications/env/helmfile.yaml --environment stg apply --suppress-secrets

# env-dev:
#  stage: deploy
#  image:
#     name: registry.gitlab.sysf.one/docker/image/helmfile:latest
#     entrypoint: [""]
#  environment: dev
#  tags:
#     - kubernetes
#  script:
#    - export SYS_HELM_NEW="true"
#    - kubectl create namespace env-dev || true
#    - kubectl label --overwrite ns env-dev env=true
#    - kubectl label --overwrite ns env-dev namespace-node-affinity=enabled
#    - kubectl config set-context --current --namespace=env-dev
#    - "kubectl get secret sys-env-var-config-dev --namespace=default -o yaml | sed 's/namespace: default/namespace: env-dev/' | sed 's/name: sys-env-var-config-dev/name: sys-env-var-config/' | kubectl apply --namespace=env-dev -f - || true"
#    - helmfile --file applications/env/helmfile.yaml --environment dev apply --suppress-secrets

# env-ide1:
#  stage: deploy
#  image:
#     name: registry.gitlab.sysf.one/docker/image/helmfile:latest
#     entrypoint: [""]
#  environment: ide1
#  tags:
#     - kubernetes
#  script:
#    - export SYS_HELM_NAMESPACE_SUFFIX=ide1
#    - export SYS_HELM_NEW="false"
#    - kubectl create namespace env-ide1 || true
#    - kubectl label --overwrite ns env-ide1 env=true
#    - kubectl label --overwrite ns env-ide1 namespace-node-affinity=enabled
#    - kubectl config set-context --current --namespace=env-ide1
#    - "kubectl get secret sys-env-var-config-ide --namespace=default -o yaml | sed 's/namespace: default/namespace: env-ide1/' | sed 's/name: sys-env-var-config-ide/name: sys-env-var-config/' | kubectl apply --namespace=env-ide1 -f - || true"
#    - helmfile --file applications/env/helmfile.yaml --environment ide apply --suppress-secrets

