stages:
  - deploy

before_script:
  - env
  - uname -a

admin:
  stage: deploy
  image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.3.2"
  environment: admin
  script:
    - gl-helmfile --environment admin apply --suppress-secrets

# gitlab:
#   stage: deploy
#   image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.3.2"
#   environment: gitlab
#   script:
#     - gl-helmfile --environment gitlab apply --suppress-secrets

env-prd:
 stage: deploy
 image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.3.2"
 environment: prd
 script:
   - gl-ensure-namespace env-prd
   - export SYS_HELM_NEW="true"
   - kubectl config set-context --current --namespace=env-prd
   - "kubectl get secret ssh-config --namespace=default -o yaml | sed 's/namespace: default/namespace: env-prd/' | kubectl apply --namespace=env-prd -f - || true"
   - "kubectl get secret tls-sys --namespace=default -o yaml | sed 's/namespace: default/namespace: env-prd/' | kubectl apply --namespace=env-prd -f - || true"
   - "kubectl get secret mariadb --namespace=default -o yaml | sed 's/namespace: default/namespace: env-prd/' | kubectl apply --namespace=env-prd -f - || true"
   - "kubectl get secret sys-env-var-config-prd --namespace=default -o yaml | sed 's/namespace: default/namespace: env-prd/' | sed 's/name: sys-env-var-config-prd/name: sys-env-var-config/' | kubectl apply --namespace=env-prd -f - || true"
   - gl-helmfile --environment prd apply --suppress-secrets

# env-stg:
#  stage: deploy
#  image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.3.2"
#  environment: stg
#  script:
#    - gl-ensure-namespace env-stg
#    - export SYS_HELM_NEW="false"
#    - kubectl config set-context --current --namespace=env-stg
#    - "kubectl get secret ssh-config --namespace=default -o yaml | sed 's/namespace: default/namespace: env-stg/' | kubectl apply --namespace=env-stg -f - || true"
#    - "kubectl get secret tls-sys --namespace=default -o yaml | sed 's/namespace: default/namespace: env-stg/' | kubectl apply --namespace=env-stg -f - || true"
#    - "kubectl get secret mariadb --namespace=default -o yaml | sed 's/namespace: default/namespace: env-stg/' | kubectl apply --namespace=env-stg -f - || true"
#    - "kubectl get secret sys-env-var-config-stg --namespace=default -o yaml | sed 's/namespace: default/namespace: env-stg/' | sed 's/name: sys-env-var-config-stg/name: sys-env-var-config/' | kubectl apply --namespace=env-stg -f - || true"
#    - gl-helmfile --environment stg apply --suppress-secrets

# env-dev:
#  stage: deploy
#  image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.3.2"
#  environment: dev
#  script:
#    - gl-ensure-namespace env-dev
#    - export SYS_HELM_NEW="true"
#    - kubectl config set-context --current --namespace=env-dev
#    - "kubectl get secret ssh-config --namespace=default -o yaml | sed 's/namespace: default/namespace: env-dev/' | kubectl apply --namespace=env-dev -f - || true"
#    - "kubectl get secret tls-sys --namespace=default -o yaml | sed 's/namespace: default/namespace: env-dev/' | kubectl apply --namespace=env-dev -f - || true"
#    - "kubectl get secret mariadb --namespace=default -o yaml | sed 's/namespace: default/namespace: env-dev/' | kubectl apply --namespace=env-dev -f - || true"
#    - "kubectl get secret sys-env-var-config-dev --namespace=default -o yaml | sed 's/namespace: default/namespace: env-dev/' | sed 's/name: sys-env-var-config-dev/name: sys-env-var-config/' | kubectl apply --namespace=env-dev -f - || true"
#    - gl-helmfile --environment dev apply --suppress-secrets

env-ide1:
 stage: deploy
 image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.3.2"
 environment: ide1
 script:
   - export SYS_HELM_NAMESPACE_SUFFIX=ide1
   - export SYS_HELM_NEW="false"
   - gl-ensure-namespace env-ide1
   - kubectl config set-context --current --namespace=env-ide1
   - "kubectl get secret ssh-config --namespace=default -o yaml | sed 's/namespace: default/namespace: env-ide1/' | kubectl apply --namespace=env-ide1 -f - || true"
   - "kubectl get secret tls-sys --namespace=default -o yaml | sed 's/namespace: default/namespace: env-ide1/' | kubectl apply --namespace=env-ide1 -f - || true"
   - "kubectl get secret mariadb --namespace=default -o yaml | sed 's/namespace: default/namespace: env-ide1/' | kubectl apply --namespace=env-ide1 -f - || true"
   - "kubectl get secret sys-env-var-config-ide --namespace=default -o yaml | sed 's/namespace: default/namespace: env-ide1/' | sed 's/name: sys-env-var-config-ide/name: sys-env-var-config/' | kubectl apply --namespace=env-ide1 -f - || true"
   - gl-helmfile --environment ide apply --suppress-secrets
