helmDefaults:
  cleanupOnFail: false

helmfiles:

  # Kong.
  # - path: applications/kong/kong/helmfile.yaml

  # Admin / one.
  - path: applications/admin/kube-prometheus/helmfile.yaml
  - path: applications/admin/cert-manager/helmfile.yaml
  - path: applications/admin/nginx-ingress/helmfile.yaml
  - path: applications/admin/grafana/helmfile.yaml
  - path: applications/admin/keycloak/helmfile.yaml
  - path: applications/admin/keycloak-postgresql/helmfile.yaml
  - path: applications/admin/elasticsearch/helmfile.yaml
  - path: applications/admin/fluentd/helmfile.yaml
  - path: applications/admin/kubernetes-dashboard/helmfile.yaml

  # Env / many.
  - path: applications/env/helmfile.yaml

  # rook-ceph.
  - path: applications/rook-ceph/rook-ceph/helmfile.yaml
  - path: applications/rook-ceph/rook-ceph-cluster/helmfile.yaml

  # Gitlab.
  - path: applications/gitlab/gitlab/helmfile.yaml

  # Gitlab runners.
  - path: applications/gitlab-runner/gitlab-runner-kubernetes/helmfile.yaml
  - path: applications/gitlab-runner/gitlab-runner-docker/helmfile.yaml

  # Ops.
  - path: applications/ops/kubefledged/helmfile.yaml
  - path: applications/ops/kubed/helmfile.yaml
  # - path: applications/ops/gke-preemptible-killer/helmfile.yaml
  - path: applications/ops/nfs-server-provisioner/helmfile.yaml
  # - path: applications/ops/nfs-subdir-external-provisioner/helmfile.yaml

environments:
  prd: {  }
  stg: {  }
  dev: {  }
  cid: {  }
  ide: {  }
  # kong: {  }
  admin: {  }
  rook-ceph: {  }
  gitlab: {  }
  gitlab-runner: {  }
  ops: {  }
