helmDefaults:
  cleanupOnFail: false

helmfiles:

  # Admin / one.
  # - path: applications/admin/cert-manager/helmfile.yaml
  - path: applications/admin/nginx-ingress-controller/helmfile.yaml
  - path: applications/admin/kube-prometheus/helmfile.yaml
  - path: applications/admin/grafana/helmfile.yaml
  - path: applications/admin/keycloak/helmfile.yaml
  - path: applications/admin/elasticsearch/helmfile.yaml
  - path: applications/admin/fluentd/helmfile.yaml
  - path: applications/admin/kubernetes-dashboard/helmfile.yaml

  # Env / many.
  - path: applications/env/cluster-cache/helmfile.yaml
  - path: applications/env/mariadb-galera/helmfile.yaml
  - path: applications/env/redis-cluster/helmfile.yaml
  - path: applications/env/elasticsearch/helmfile.yaml
  - path: applications/env/nginx-php-fpm/helmfile.yaml
  - path: applications/env/node/helmfile.yaml

  # rook-ceph.
  - path: applications/rook-ceph/rook-ceph/helmfile.yaml
  - path: applications/rook-ceph/rook-ceph-cluster/helmfile.yaml

  # Gitlab.
  - path: applications/gitlab/gitlab/helmfile.yaml

  # Ops.
  - path: applications/ops/gitlab-runner-kubernetes/helmfile.yaml
  - path: applications/ops/gitlab-runner-docker/helmfile.yaml
  - path: applications/ops/kubefledged/helmfile.yaml
  - path: applications/ops/kubed/helmfile.yaml
  - path: applications/ops/gke-preemptible-killer/helmfile.yaml
  - path: applications/ops/nfs-server-provisioner/helmfile.yaml
  # - path: applications/ops/nfs-subdir-external-provisioner/helmfile.yaml
  # - path: applications/ops/reflector/helmfile.yaml

environments:
  prd: {  }
  stg: {  }
  dev: {  }
  cid: {  }
  ide: {  }
  admin: {  }
  rook-ceph: {  }
  gitlab: {  }
  ops: {  }
