repositories:
  - name: gitlab
    url: https://charts.gitlab.io

releases:
  - name: gitlab-runner-kubernetes
    namespace: gitlab
    chart: gitlab/gitlab-runner
    version: 0.38.0
    installed: true

    values:
      - values.yaml

environments:
  gitlab: {  }
