auth:
  adminPassword: drupal
  managementPassword: drupal

postgresql:
  postgresqlPassword: "drupal"
  postgresqlPostgresPassword: drupal
  persistence:
    enabled: true
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: id.sys.sysf.one
  tls: true
  certManager: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://id.sys.sysf.one/auth"

metrics:
  enabled: true

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
          - default-pool
