auth:
  adminUser: user
  adminPassword: drupal

postgresql:
  auth:
    postgresPassword: drupal
    password: drupal
  primary:
    persistence:
      size: 8Gi
      storageClass: efs-sc-1001
      accessModes:
        - ReadWriteMany

# postgresql:
#   enabled: false

# externalDatabase:
#   host: postgresql
#   user: drupal
#   password: drupal
#   database: bitnami_keycloak

service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: id.sys.sysf.one
  tls: true
  certManager: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.org/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
# extraEnvVars:
  # - name: KEYCLOAK_EXTRA_ARGS
  #   value: "-Dkeycloak.frontendUrl=https://id.sys.sysf.one"

# keycloakConfigCli:
#   enabled: false

metrics:
  enabled: true

# logging:
#   level: DEBUG

# image:
#   debug: true
