auth:
  adminUser: user
  adminPassword: drupal
  managementPassword: drupal

postgresql:
  enabled: false

externalDatabase:
  host: postgresql
  user: drupal
  password: drupal
  database: bitnami_keycloak

service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: id.sys.sysf.one
  tls: true
  certManager: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://id.sys.sysf.one/auth"

keycloakConfigCli:
  enabled: false

metrics:
  enabled: true
