auth:
  adminPassword: drupal
  managementPassword: drupal

postgresql:
  postgresqlPassword: "drupal"
  postgresqlPostgresPassword: drupal
  persistence:
    enabled: true
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: id.sys.sysf.one
  tls: true
  certManager: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: tls-sys

extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://id.sys.sysf.one/auth"
