apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-gce-pd-snapshot-class-with-storage-locations
  annotations:
    k10.kasten.io/is-snapshot-class: 'true'
parameters:
  storage-locations: us-east4
driver: pd.csi.storage.gke.io
deletionPolicy: Delete
