apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-gce-pd-snapshot-class-with-storage-locations
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "false"
parameters:
  storage-locations: us-east4
driver: pd.csi.storage.gke.io
deletionPolicy: Delete
