helmDefaults:
  wait: false
  cleanupOnFail: false

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: redis-cluster
    namespace: env-{{ env "SYS_HELM_NAMESPACE_SUFFIX" | default .Environment.Name }}
    chart: bitnami/redis-cluster
    version: 8.1.3
    installed: true
    values:
      - values.yaml
      - env/{{ .Environment.Name }}/values.yaml
      # - cluster:
      #     init: {{ env "SYS_HELM_NEW" | default "false" }}

environments:
  prd: {  }
  stg: {  }
  dev: {  }
  cid: {  }
  ide: {  }
