password: "drupal"
global:
  redis:
    password: "drupal"

persistence:
  enabled: true
  storageClass: standard-rwo
  accessModes:
    - ReadWriteOnce

cluster:
  nodes: 1
  update:
    addNodes: true
    currentNumberOfNodes: 1
