password: "drupal"
global:
  redis:
    password: "drupal"

redis:
  configmap: "dir /mnt/data"
  extraVolumeMounts:
    - mountPath: "/mnt/data"
      name: "redis-data-memory"
  extraVolumes:
    - name: "redis-data-memory"
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - default-pool

containerSecurityContext:
  runAsUser: 0
  runAsNonRoot: false
  privileged: true

persistence:
  storageClass: ceph-block
  accessModes:
    - ReadWriteOnce

cluster:
  nodes: 6
  init: true
