password: "drupal"
global:
  redis:
    password: "drupal"

redis:
  configmap: "cluster-config-file /bitnami/volume/nodes.conf"
  extraVolumeMounts:
    - mountPath: "/bitnami/redis/data"
      name: "redis-data-memory"
  extraVolumes:
    - name: "redis-data-memory"
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - default-pool

containerSecurityContext:
  runAsUser: 0
  runAsNonRoot: false
  privileged: true

persistence:
  path: "/bitnami/volume"
  storageClass: ceph-filesystem
  accessModes:
    - ReadWriteMany

cluster:
  nodes: 6
  init: false
