password: "drupal"
global:
  redis:
    password: "drupal"

redis:
  configmap: "dir /mnt/data"
  extraVolumeMounts:
    - mountPath: "/mnt/data"
      name: "redis-data-memory"
  extraVolumes:
    - name: "redis-data-memory"
      emptyDir:
        medium: Memory
        sizeLimit: 1Gi

containerSecurityContext:
  runAsUser: 0
  runAsNonRoot: false
  privileged: true

persistence:
  storageClass: ceph-filesystem
  accessModes:
    - ReadWriteMany

cluster:
  nodes: 6
  init: true
