password: "drupal"
global:
  redis:
    password: "drupal"

redis:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - default-pool

persistence:
  enabled: false
  storageClass: ceph-filesystem
  accessModes:
    - ReadWriteMany

cluster:
  nodes: 6
  init: false
