gitlabUrl: https://gitlab.sysf.one/
runnerRegistrationToken: "NUuLRmkTVpuPP4OfPm5o3QUAV48kn1CfhQtQiicWxUlm5bsMe2XilV6Svi5LLbl4"
concurrent: 10
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
          - default-pool
secrets:
  - name: google-application-credentials
rbac:
  create: true
  rules: []
  clusterWideAccess: true
  podSecurityPolicy:
    enabled: false
    resourceNames:
    - gitlab-runner
metrics:
  enabled: true
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: true
runners:
  cache:
      secretName: google-application-credentials
  tags: "sysf,ssh"
  runUntagged: false
  config: |
    [[runners]]
      executor = "ssh"
      [runners.ssh]
        host = "web-nginx-php-fpm.env-prd.cluster.local"
        port = "22"
        user = "www-data"
        identity_file = "/root/.ssh-workaround/id_rsa"
        disable_strict_host_key_checking = false
        [[runners.ssh.volumes.secret]]
          name = "ssh-config"
          mount_path = "/root/.ssh-workaround"
          read_only = true
