repositories:
  - name: kong
    url: https://charts.konghq.com

releases:
  - name: kong
    namespace: kong
    chart: kong/kong
    version: 2.13.1
    installed: true
    values:
      - values.yaml

environments:
  kong: {  }
