repositories:
  - name: kong
    url: https://charts.konghq.com

releases:
  - name: kong
    namespace: kong
    chart: kong/kong
    # version: 9.2.28
    installed: true
    values:
      - values.yaml

environments:
  kong: {  }
