repositories:
  - name: gitlab
    url: https://charts.gitlab.io

releases:
  - name: gitlab-runner
    namespace: admin
    chart: gitlab/gitlab-runner
    installed: true

    values:
      - values.yaml

environments:
  admin: {  }
