apiVersion: actions.kio.kasten.io/v1alpha1
kind: RestoreAction
metadata:
  generateName: restore-admin-
  namespace: admin
spec:
  subject:
    kind: RestorePoint
    name: scheduled-89b9j
    namespace: admin
  targetNamespace: admin