---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-cache-composer
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem
