---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: admin
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'bryan.jiencke@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-account-key-staging
    solvers:
    - dns01:
        cloudDNS:
          project: bdbd-310322
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: admin
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'bryan.jiencke@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-account-key-staging
    solvers:
    - dns01:
        cloudDNS:
          project: bdbd-310322
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sysf.one-staging-tls
  namespace: admin
spec:
  secretName: sysf.one-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - 'sysf.one'
  - '*.sysf.one'
  - '*.sys.sysf.one'
  - '*.env.sys.sysf.one'
  - '*.app.sys.sysf.one'
  - '*.platform.sys.sysf.one'
  - '*.network.sys.sysf.one'
  - '*.gitlab.sysf.one'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: systemf.one-staging-tls
  namespace: admin
spec:
  secretName: systemf.one-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - 'systemf.one'
  - '*.systemf.one'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: theentityframework.com-staging-tls
  namespace: admin
spec:
  secretName: theentityframework.com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - 'theentityframework.com'
  - '*.theentityframework.com'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bryanjiencke.com-staging-tls
  namespace: admin
spec:
  secretName: bryanjiencke.com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - 'bryanjiencke.com'
  - '*.bryanjiencke.com'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stevenjiencke.com-staging-tls
  namespace: admin
spec:
  secretName: stevenjiencke.com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - 'stevenjiencke.com'
  - '*.stevenjiencke.com'
