apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  source: "sys.k8s"

resources:
  # - cronjob/service-account.yml
  # - cronjob/pod-maintain.yml
  - gitlab/service-account.yml
  - gitlab/dind.yaml
  - gitlab/image-cache.yaml
  - prometheus/podmonitor.yml
  - cluster-issuer-prod.yml
  - gitlab-postgresql.yml
#  - gitlab/omniauth-keycloak-secret.yaml
