---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-storage--env-prd
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.136.15.87
    path: "/export/pvc-47add5ba-94d7-485e-b347-5416cf04ef50"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-storage
  namespace: env-prd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: cluster-storage--env-prd
