---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-storage
  namespace: ops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 50Gi
