---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-storage--env-ide1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server-provisioner-0.nfs-server-provisioner.ops.svc.cluster.local
    path: "/export"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-storage
  namespace: env-ide1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: cluster-storage--env-ide1
