allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: nfs-server-provisioner-admin
    meta.helm.sh/release-namespace: env-admin
  creationTimestamp: "2021-10-13T12:41:02Z"
  labels:
    app: nfs-server-provisioner
    app.kubernetes.io/managed-by: Helm
    chart: nfs-server-provisioner-1.1.3
    heritage: Helm
    release: nfs-server-provisioner-admin
  name: nfs-admin
mountOptions:
- vers=4
provisioner: cluster.local/nfs-server-provisioner-admin
reclaimPolicy: Retain
volumeBindingMode: Immediate
