---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-storage--env-prd
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.136.11.122
    path: "/export/pvc-349f0caf-33c7-4ad5-9478-4d6e4a51d9dd"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-storage
  namespace: env-prd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: cluster-storage--env-prd
