---
apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
  namespace: rook-ceph
spec:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: k8s.sysf.one/nodegroup
  #           operator: In
  #           values:
  #           - persistent
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: dataaccess
#   namespace: ops
# spec:
#   # affinity:
#   #   nodeAffinity:
#   #     requiredDuringSchedulingIgnoredDuringExecution:
#   #       nodeSelectorTerms:
#   #       - matchExpressions:
#   #         - key: k8s.sysf.one/nodegroup
#   #           operator: In
#   #           values:
#   #           - persistent
#   containers:
#   - name: alpine
#     image: alpine:latest
#     command: ['sleep', 'infinity']
