apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: data-keycloak-postgresql-0
      mountPath: /data
  volumes:
  - name: data-keycloak-postgresql-0
    persistentVolumeClaim:
      claimName: data-keycloak-postgresql-0
