apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
  namespace: rook-ceph
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem
