apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql-workaround-efs
  namespace: admin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
