apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql-workaround-gp2
  namespace: admin
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
