aggregator:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - default-pool
  configMap: elasticsearch-output
  extraEnvVars:
    - name: ELASTICSEARCH_HOST
      value: "elasticsearch-coordinating-only.admin.svc.cluster.local"
    - name: ELASTICSEARCH_PORT
      value: "9200"

forwarder:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - default-pool
  configMap: fluentd-forwarder
  extraEnvVars:
    - name: FLUENTD_DAEMON_USER
      value: "root"
    - name: FLUENTD_DAEMON_GROUP
      value: "root"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
