aggregator:
  configMap: elasticsearch-output
  extraEnvVars:
    - name: ELASTICSEARCH_HOST
      value: "elasticsearch-coordinating-only.admin.svc.cluster.local"
    - name: ELASTICSEARCH_PORT
      value: "9200"

forwarder:
  configMap: fluentd-forwarder
  extraEnvVars:
    - name: FLUENTD_DAEMON_USER
      value: "root"
    - name: FLUENTD_DAEMON_GROUP
      value: "root"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
