daemonset:
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1000m"
      memory: "200Mi"
  filebeatConfig:
    filebeat.yml: |

      # filebeat.modules:

      # - module: system
      #   syslog:
      #     enabled: true
      #     var.paths: ["/var/log/pods/*/syslog"]
      #   auth:
      #     enabled: true
      #     tags:
      #       - syslog
      #       - auth
      #     var.paths: ["/var/log/pods/*/auth.syslog.log"]

      # - module: system
      #   auth:
      #     enabled: true
      #     var.paths: ["/var/log/pods/*/auth.syslog.log"]
      #     var.convert_timezone: true
      #     input:
      #       tags:
      #         - syslog
      #         - auth
      #     processors:
      #       - add_kubernetes_metadata:
      #           host: ${NODE_NAME}

      filebeat.inputs:

      - type: log
        tags:
          - syslog
          - auth
        paths:
          - '/var/log/pods/*/auth.syslog.log'

      - type: container
        tags:
          - k8s
          - docker
          - container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

      - type: log
        tags:
          - syslog
          - drupal
          - watchdog
        paths:
          - '/var/log/pods/*/drupal.syslog.log'

      - type: log
        tags:
          - syslog
          - drupal
          - php-fpm
        paths:
          - '/var/log/pods/*/php-fpm.syslog.log'

      - type: log
        tags:
          - syslog
          - user
        paths:
          - '/var/log/pods/*/user.syslog.log'

      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'

deployment:
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1000m"
      memory: "200Mi"
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: tcp
        max_message_size: 10MiB
        host: "localhost:9000"

      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
