repositories:
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

releases:
  - name: nfs-subdir-external-provisioner
    namespace: env-{{ .Environment.Name }}
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    installed: true

    values:
      - values.yaml

environments:
  k10: {  }
