global:
  persistence:
    enabled: true
    storageClass: do-block-storage

ingress:
  create: true
  host: "k10.sys.sysf.one"
  urlPath: "/k10"
  tls:
    enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx

auth:
  tokenAuth:
    enabled: false
  oidcAuth:
    enabled: true
    secretName: k10-oidc-auth

prometheus:
  server:
    persistentVolume:
      enabled: false
