global:
  persistence:
    enabled: true
    storageClass: standard-rwo

ingress:
  create: true
  host: "k10.sys.sysf.one"
  urlPath: "/k10"
  tls:
    enabled: true
    secretName: tls-sys
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: tls-sys

auth:
  tokenAuth:
    enabled: true
  oidcAuth:
    enabled: false
    secretName: k10-oidc-auth

prometheus:
  server:
    enabled: false
    persistentVolume:
      enabled: false

grafana:
  enabled: false
