helmDefaults:
  recreatePods: true

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: grafana
    namespace: admin
    chart: bitnami/grafana
    version: 6.3.3
    installed: true

    values:
      - values.yaml

environments:
  admin: {  }
