persistence:
  enabled: true
  storageClass: ceph-filesystem
  accessMode: ReadWriteMany

ingress:
  enabled: true
  hostname: grafana.sys.sysf.one
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: tls-sys

admin:
  user: "admin"
  password: "drupal"

grafana:

  podSecurityContext:
    runAsUser: 0
    runAsNonRoot: false

  extraVolumes:
  - name: config-grafana
    secret:
      secretName: config-grafana

  extraVolumeMounts:
  - name: config-grafana
    mountPath: /opt/bitnami/grafana/conf/grafana.ini
    subPath: grafana.ini

plugins: "redis-datasource"

metrics:
  enabled: true
