persistence:
  enabled: true
  size: 10Gi

ingress:
  enabled: true
  hostname: grafana.admin.sys.sysf.one
  tls: false
  annotations:
    kubernetes.io/ingress.class: nginx

admin:
  user: "admin"
  password: "drupal"

extraVolumes:
- name: config-grafana 
  secret:
    secretName: config-grafana 

extraVolumeMounts:
- name: config-grafana 
  mountPath: /opt/bitnami/grafana/conf/grafana.ini
  subPath: grafana.ini
