apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: env-admin
commonLabels:
  app: preemptible-killer
bases:
- github.com/estafette/estafette-gke-preemptible-killer//manifests
images:
- name: estafette/estafette-gke-preemptible-killer
  newTag: 1.1.21