helmDefaults:
  wait: false
  cleanupOnFail: false

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: elasticsearch
    namespace: env-{{ env "SYS_HELM_NAMESPACE_SUFFIX" | default .Environment.Name }}
    chart: bitnami/elasticsearch
    version: 19.5.5
    installed: true
    values:
      - values.yaml
      - env/{{ .Environment.Name }}/values.yaml

environments:
  prd: {  }
  stg: {  }
  dev: {  }
  cid: {  }
  ide: {  }
