data:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 80
  resources:
    limits: {}
    requests:
      cpu: 200m
      memory: 512Mi
  persistence:
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

master:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 80
  resources:
    limits: {}
    requests:
      cpu: 200m
      memory: 512Mi
  persistence:
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

coordinating:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 80
  resources:
    limits: {}
    requests:
      cpu: 200m
      memory: 512Mi
