gitlabUrl: https://gitlab.sysf.one/
runnerRegistrationToken: "yh1BRTKTgeBeaVzQ1r6G8FGzMamvs4WvE4fFgn2gI8Eg2jrzl2guNmNOtgyDyIct"
concurrent: 10
secrets:
  - name: google-application-credentials
rbac:
  create: true
  rules: []
  clusterWideAccess: true
  podSecurityPolicy:
    enabled: false
    resourceNames:
    - gitlab-runner
service:
  enabled: true
metrics:
  enabled: true
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: false
runners:
  cache:
      secretName: google-application-credentials
  tags: "sysf,kubernetes"
  runUntagged: false
  config: |
    [[runners]]
      [runners.kubernetes]
        privileged = true
        [runners.cache]
          Type = "gcs"
          Path = "kubernetes"
          Shared = true
          [runners.cache.gcs]
            BucketName = "sysf-12-gitlab-runners-cache"
        [[runners.kubernetes.volumes.secret]]
          name = "ssh-config"
          mount_path = "/root/.ssh-workaround"
          read_only = true
