helmDefaults:
  wait: true

persistence:
  enabled: true
  storageClass: efs-sc-1001
  accessMode: ReadWriteMany
  size: 20Gi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 80

extraVolumes:
  - name: cluster-cache
    persistentVolumeClaim:
      claimName: cluster-cache-cluster-storage-connector
      readOnly: false

imagePullSecrets:
  - name: gitlab-pull-secret

phpfpm:
  extraVolumeMounts:
  - name: cluster-cache
    mountPath: /mnt/cluster-cache
  resources:
    limits: {}
    requests:
      cpu: 50m
      memory: 512Mi
  extraEnvVars: {}
nginx:
  resources:
    limits: {}
    requests:
      cpu: 50m
      memory: 64Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/default-backend: fallback-backend
