helmDefaults:
  wait: true

persistence:
  enabled: true
  storageClass: ceph-filesystem
  accessMode: ReadWriteMany
  size: 50Gi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 80

extraVolumes:
  - name: sysf-one-tls
    secret:
      secretName: sysf.one-tls
  - name: cluster-cache
    persistentVolumeClaim:
      claimName: cluster-cache-cluster-storage-connector
      readOnly: false

imagePullSecrets:
  - name: gitlab-pull-secret

phpfpm:
  extraVolumeMounts:
    - name: cluster-cache
      mountPath: /mnt/cluster-cache
  resources:
    limits: {}
    requests:
      cpu: 50m
      memory: 2048Mi
  extraEnvVars: {}
nginx:
  extraVolumeMounts:
    - mountPath: "/etc/letsencrypt/sysf.one"
      name: sysf-one-tls
      readOnly: true
  resources:
    limits: {}
    requests:
      cpu: 50m
      memory: 256Mi

ingress:
  enabled: false
