apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-bryan
  namespace: gitlab
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 8Ti 
