data:
  replicas: 2
  persistence:
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

master:
  replicas: 1
  persistence:
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

coordinating:
  replicas: 1
