data:
  # autoscaling:
  #   enabled: true
  #   minReplicas: 2
  #   maxReplicas: 5
  #   targetCPU: 90
  resources:
    limits: {}
    requests:
      cpu: 100m
      memory: 128Mi
  persistence:
    storageClass: efs-sc
    accessModes:
      - ReadWriteMany

master:
  # autoscaling:
  #   enabled: true
  #   minReplicas: 2
  #   maxReplicas: 5
  #   targetCPU: 90
  resources:
    limits: {}
    requests:
      cpu: 100m
      memory: 128Mi
  persistence:
    storageClass: efs-sc
    accessModes:
      - ReadWriteMany

coordinating:
  # autoscaling:
  #   enabled: true
  #   minReplicas: 2
  #   maxReplicas: 5
  #   targetCPU: 90
  resources:
    limits: {}
    requests:
      cpu: 100m
      memory: 128Mi

ingest:
  # autoscaling:
  #   enabled: true
  #   minReplicas: 2
  #   maxReplicas: 5
  #   targetCPU: 90
  resources:
    limits: {}
    requests:
      cpu: 100m
      memory: 128Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
