data:
  replicas: 1
  persistence:
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany
  resources:
    limits: {}
    requests:
      cpu: 25m
      memory: 1024Mi

master:
  replicas: 1
  persistence:
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

coordinating:
  replicas: 1
