helmDefaults:
  wait: true

persistence:
  enabled: true
  storageClass: ceph-filesystem
  accessMode: ReadWriteMany
  size: 50Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPU: 80

replicas: 1

phpfpm:
  resources:
    limits: {}
    requests:
      cpu: 1000m
      memory: 2048Mi

nginx:
  resources:
    limits: {}
    requests:
      cpu: 500m
      memory: 1024Mi
