helmDefaults:
  wait: true

persistence:
  enabled: true
  storageClass: ceph-filesystem
  accessMode: ReadWriteMany
  size: 50Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPU: 90

replicas: 1

phpfpm:
  resources:
    requests: {}
    limits:
      cpu: 2000m
      memory: 2048Mi

nginx:
  resources:
    requests: {}
    limits:
      cpu: 1000m
      memory: 1024Mi
