persistence:
  enabled: true
  storageClass: ceph-filesystem
  accessMode: ReadWriteMany
  size: 50Gi

autoscaling:
  enabled: true
  minReplica: 2
  maxReplica: 11
  targetCPU: 80
  targetMemory: 80
