helmDefaults:
  wait: true

persistence:
  enabled: true
  storageClass: ceph-filesystem
  accessMode: ReadWriteMany
  size: 50Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPU: 90

replicas: 1

phpfpm:
  resources:
    limits: {}
    requests:
      cpu: 1000m
      memory: 512Mi

nginx:
  resources:
    limits: {}
    requests:
      cpu: 200m
      memory: 256Mi
