repositories:
  - name: gitlab
    url: https://charts.gitlab.io

releases:
  - name: gitlab
    namespace: gitlab
    chart: gitlab/gitlab
    version: 6.1.2
    timeout: 6000
    installed: true

    values:
      - values.yaml

environments:
  gitlab: {  }
