global:
  grafana:
    enabled: false
  hosts:
    domain: sysf.one
    # hostSuffix: staging
    https: true
    gitlab:
      name: gitlab.sysf.one
      https: true
    registry:
      name: registry.gitlab.sysf.one
      https: true
    minio:
      name: minio.gitlab.sysf.one
      https: true
    smartcard:
      name: smartcard.gitlab.sysf.one
      https: true
    kas:
      name: kas.gitlab.sysf.one
      https: true
    pages:
      name: pages.gitlab.sysf.one
      https: true
    ssh: gitlab.sysf.one
  ingress:
    configureCertmanager: false
    class: nginx
    # annotations:
    #   # kubernetes.io/ingress.class: nginx
    #   cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      enabled: true
      secretName: sysf.one-tls
  gitlab_kas:
    enabled: false
  appConfig:
    omniauth:
      enabled: true
      syncProfileFromProvider: true
      blockAutoCreatedUsers: false
      allowSingleSignOn: true
      autoSignInWithProvider: openid_connect
      providers:
        - secret: gitlab-sso-oidc
certmanager-issuer:
  email: bryan.jiencke@gmail.com
certmanager:
  install: false
gitlab-runner:
  install: false
pages:
  enabled: true
prometheus:
  install: false
postgresql:
  persistence:
    accessModes:
      - ReadWriteMany
  metrics:
    enabled: false
minio:
  persistence:
    accessMode: ReadWriteMany
nginx-ingress:
  enabled: false
redis:
  master:
    persistence:
      accessModes:
        - ReadWriteMany
  replica:
    persistence:
      accessModes:
        - ReadWriteMany
gitlab:
  gitaly:
    persistence:
      accessMode: ReadWriteMany
