repositories:
  - name: gitlab
    url: https://charts.gitlab.io

releases:
  - name: gitlab-runner-docker
    namespace: gitlab-runner
    chart: gitlab/gitlab-runner
    # version: 0.43.1
    installed: true
    values:
      - values.yaml

environments:
  gitlab-runner: {  }
