image:
  registry: registry.gitlab.com
  image: gitlab-org/gitlab-runner
  tag: alpine-v15.2.1
gitlabUrl: https://gitlab.sysf.one/
runnerRegistrationToken: "zegBg7An0Xv8c4ODbx0knhIdKaIkduB9envF33JvcAnT7a1hw7WaWtoglA280HId"
concurrent: 10
secrets:
  - name: google-application-credentials
rbac:
  create: true
  rules: []
  clusterWideAccess: true
  podSecurityPolicy:
    enabled: false
    resourceNames:
    - gitlab-runner
service:
  enabled: true
metrics:
  enabled: true
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: false
runners:
  helpers:
    image: "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-32fc1585"
  cache:
      secretName: google-application-credentials
  tags: "sysf,docker"
  runUntagged: true
  config: |
    [[runners]]
      executor = "docker"
      [runners.docker]
        privileged = true
        [runners.cache]
          Type = "gcs"
          Path = "docker"
          Shared = true
          [runners.cache.gcs]
            BucketName = "sysf-12-gitlab-runners-cache"
