gitlabUrl: https://gitlab.sysf.one/
runnerRegistrationToken: "NUuLRmkTVpuPP4OfPm5o3QUAV48kn1CfhQtQiicWxUlm5bsMe2XilV6Svi5LLbl4"
concurrent: 10
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
          - default-pool
secrets:
  - name: google-application-credentials
rbac:
  create: true
  rules: []
  clusterWideAccess: true
  podSecurityPolicy:
    enabled: false
    resourceNames:
    - gitlab-runner
metrics:
  enabled: true
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: true
runners:
  config: |
    [[runners]]
      executor = "docker"
      [runners.docker]
        privileged = true
        [runners.cache]
          Type = "gcs"
          Path = "docker"
          Shared = true
          [runners.cache.gcs]
            BucketName = "sysf-12-gitlab-runners-cache"
  cache:
      secretName: google-application-credentials
  tags: "sysf,docker"
  runUntagged: true
