repositories:
  - name: kubefledged-charts
    url: https://senthilrch.github.io/kubefledged-charts/

releases:
  - name: kubefledged
    namespace: ops
    chart: kubefledged-charts/kube-fledged
    installed: true
    values:
      - values.yaml

environments:
  ops: {  }
