helmDefaults:
  wait: false
  cleanupOnFail: false

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: node
    namespace: env-{{ env "SYS_HELM_NAMESPACE_SUFFIX" | default .Environment.Name }}
    chart: bitnami/node
    # version: 17.0.17
    installed: true
    values:
      - values.yaml
      - env/{{ .Environment.Name }}/values.yaml

environments:
  prd: {  }
  stg: {  }
  dev: {  }
  cid: {  }
  ide: {  }
