persistence:
  enabled: true
  accessMode: ReadWriteMany
mongodb:
  enabled: true
  persistence:
    accessModes:
      - ReadWriteMany
  auth:
    rootPassword: drupal
    username: drupal
    password: drupal
