persistence:
  enabled: true
  storageClass: ceph-block
  accessMode: ReadWriteOnce
mongodb:
  enabled: true
  auth:
    rootPassword: drupal
    username: drupal
    password: drupal

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
