sys:
  context: cloud
  subcontext: prd
  uri: https://sysf.one/

helmDefaults:
  wait: true

ingress:
  enabled: true
  hosts:
    - bryanjiencke.com
    - www.bryanjiencke.com
    - sysf.one
    - www.sysf.one
    - systemf.ome
    - www.systemf.one
    - stevenjiencke.com
    - www.stevenjiencke.com
    - theentityframework.com
    - www.theentityframework.com
