helmDefaults:
  cleanupOnFail: false

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: mariadb
    namespace: env-{{ env "SYS_HELM_NAMESPACE_SUFFIX" | default .Environment.Name }}
    chart: bitnami/mariadb
    version: 10.3.5
    installed: true

    values:
      - values.yaml
      - env/{{ .Environment.Name }}/values.yaml

environments:
  prd: {  }
  stg: {  }
  dev: {  }
  cid: {  }
  ide: {  }
