architecture: standalone

primary:
  persistence:
    enabled: true
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany
  configuration: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=32M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    key_buffer=32M
    key_buffer_size=32M
    thread_stack=256K
    thread_cache_size=256
    query_cache_limit=64M
    query_cache_size=128M
    query_cache_type=1
    join_buffer_size=16M
    read_buffer_size=16M
    sort_buffer_size=16M
    table_cache=4096
    interactive_timeout=25
    wait_timeout=1800
    connect_timeout=10
    max_connections=150

    [mysqldump]
    quick
    quote-names
    max_allowed_packet=32M

    [isamchk]
    key_buffer=16M

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

secondary:
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany
  configuration: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=32M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    key_buffer=32M
    key_buffer_size=32M
    thread_stack=256K
    thread_cache_size=256
    query_cache_limit=64M
    query_cache_size=128M
    query_cache_type=1
    join_buffer_size=16M
    read_buffer_size=16M
    sort_buffer_size=16M
    table_cache=4096
    interactive_timeout=25
    wait_timeout=1800
    connect_timeout=10
    max_connections=150

    [mysqldump]
    quick
    quote-names
    max_allowed_packet=32M

    [isamchk]
    key_buffer=16M

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

auth:
  database: drupal
  username: drupal
  existingSecret: "mariadb"
