primary:
  persistence:
    enabled: true
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

secondary:
  persistence:
    enabled: true
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

architecture: replication

auth:
  database: drupal
  username: drupal
  existingSecret: "mariadb"

# MARIADB_MASTER_ROOT_PASSWORD
