architecture: replication

primary:
  persistence:
    enabled: true
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

secondary:
  replicaCount: 5
  persistence:
    enabled: true
    storageClass: ceph-filesystem
    accessModes:
      - ReadWriteMany

auth:
  database: drupal
  username: drupal
  existingSecret: "mariadb"

# MARIADB_MASTER_ROOT_PASSWORD
