---
apiVersion: kubefledged.io/v1alpha2
kind: ImageCache
metadata:
  name: imagecache1
  namespace: ops
  labels:
    app: kubefledged
    component: imagecache
spec:
  imagePullSecrets:
  - name: gitlab-pull-secret
  cacheSpec:
  - images:
    - bitnami/elasticsearch
    - bitnami/mariadb
    - bitnami/redis-cluster
    - bitnami/node
    - bitnami/mongodb
    - registry.gitlab.sysf.one/docker/image/php-fpm
