repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kubeapps
    namespace: admin
    chart: bitnami/kubeapps
    # version: 13.0.0
    installed: true
    values:
      - values.yaml

environments:
  admin: {  }
