ingress:
  enabled: true
  hostname: kubeapps.sys.sysf.one
  pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-url: "https://oauth.sys.sysf.one/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth.sys.sysf.one/oauth2/start?rd=$scheme://$best_http_host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  tls: true
global:
  postgresql:
    auth:
      postgresPassword: "drupal"
      password: "drupal"
  redis:
    auth:
      password: "drupal"
