helmDefaults:
  recreatePods: true

repositories:
  - name: estafette
    url: https://helm.estafette.io

releases:
  - name: gke-preemptible-killer
    namespace: ops
    chart: estafette/estafette-gke-preemptible-killer
    installed: true
    values:
      - values.yaml

environments:
  ops: {  }
