service:
  loadBalancerIP: 35.199.10.52

tcp:
  22: "env-prd/web-nginx-php-fpm:22"

extraArgs:
  enable-ssl-passthrough: ""

metrics:
  enabled: true

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
          - default-pool
