service:
  # loadBalancerIP: 23.23.246.214
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-name: "sysf-nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-03f3a28093c1f9394,eipalloc-0c44b9949094d02b2

tcp:
  22: "env-prd/web-nginx-php-fpm:22"

extraArgs:
  enable-ssl-passthrough: ""

metrics:
  enabled: true

nodeSelector:
  failure-domain.beta.kubernetes.io/zone: us-east-1a

# extraVolumes:
#   - name: nginx-config
#     configMap:
#       name: nginx-test1

# extraVolumeMounts:
#   - name: nginx-config
#     mountPath: /opt/bitnami/nginx/conf/extra.conf
#     subPath: nginx.conf
