# service:
#   loadBalancerIP: 23.23.246.214
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0d11bfcbcc11ea1da

tcp:
  22: "gitlab/gitlab-gitlab-shell:22"

extraArgs:
  enable-ssl-passthrough: ""

metrics:
  enabled: true
