service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-name: "sysf-nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-096fddcfa4774690c,eipalloc-04384e0f2ab1709e1

tcp:
  22: "gitlab/gitlab-gitlab-shell:22"

extraArgs:
  enable-ssl-passthrough: ""

metrics:
  enabled: true

nodeSelector:
  failure-domain.beta.kubernetes.io/zone: us-east-2a

# extraVolumes:
#   - name: nginx-config
#     configMap:
#       name: nginx-test1

# extraVolumeMounts:
#   - name: nginx-config
#     mountPath: /opt/bitnami/nginx/conf/extra.conf
#     subPath: nginx.conf
