controller:

  setAsDefaultIngress: true

  nodeSelector:
    failure-domain.beta.kubernetes.io/zone: us-east-1a

  enableCertManager: true
  enableTLSPassthrough: true

  customPorts:
    - name: "tcp-22"
      containerPort: 22
      hostPort: 22
      protocol: TCP
    - name: "tcp-23"
      containerPort: 23
      hostPort: 23
      protocol: TCP

  globalConfiguration:
    create: true
    spec:
      listeners:
      - name: tcp-22
        port: 22
        protocol: TCP
      - name: tcp-23
        port: 23
        protocol: TCP

  service:
    customPorts:
      - name: tcp-22
        port: 22
        protocol: TCP
        targetPort: tcp-22
      - name: tcp-23
        port: 23
        protocol: TCP
        targetPort: tcp-23
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-name: "sysf-nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-03f3a28093c1f9394,eipalloc-0c44b9949094d02b2

prometheus:
  create: true
