controller:
  enableCertManager: true
  enableTLSPassthrough: true

  customPorts:
    - name: "22-tcp"
      containerPort: 22
      hostPort: 22
      protocol: TCP

  globalConfiguration:
    create: true
    spec:
      listeners:
      - name: ssh-tcp
        port: 22
        protocol: TCP
      # - name: ssh-tcp--gitlab
      #   port: 22
      #   protocol: TCP

  service:
    customPorts:
      - name: 22-tcp
        port: 22
        protocol: TCP
        targetPort: 22-tcp
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-name: "sysf-nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-03f3a28093c1f9394,eipalloc-0c44b9949094d02b2

prometheus:
  create: true
