helmDefaults:
  wait: false
  cleanupOnFail: false

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: mariadb-galera
    namespace: env-{{ env "SYS_HELM_NAMESPACE_SUFFIX" | default .Environment.Name }}
    chart: bitnami/mariadb-galera
    # version: 7.4.3
    installed: true
    values:
      - values.yaml
      - env/{{ .Environment.Name }}/values.yaml

environments:
  prd: {  }
  stg: {  }
  dev: {  }
  cid: {  }
  ide: {  }
