# Oauth client configuration specifics
config:
  clientID: "oauth2-proxy"
  clientSecret: "6DWGk7eBuUidnAnRaLXrPJZy3kVybNiT"
  # Create a new secret with the following command
  # openssl rand -base64 32 | head -c 32 | base64
  cookieSecret: "V05xTGI2TVdqN2NjQzBxOHAySjRTKy9ndTd6MnZ4YlA="
  configFile: |-
    provider = "oidc"
    provider_display_name = "Keycloak"
    oidc_issuer_url = "https://id.sys.sysf.one/realms/master"
    email_domains = [ "*" ]
    scope = "openid profile email"
    cookie_domains = [".sys.sysf.one"]
    whitelist_domains = [".sys.sysf.one"]
    pass_authorization_header = true
    pass_access_token = true
    pass_user_headers = true
    set_authorization_header = true
    set_xauthrequest = true
    cookie_refresh = "1m"
    cookie_expire = "30m"

ingress:
  enabled: true
  path: /
  hosts:
    - oauth.sys.sysf.one
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  tls:
    - secretName: oauth-proxy-tls
      hosts:
        - oauth.sys.sysf.one

redis:
  enabled: true
