sys:
  context: cloud
  subcontext: prd
  uri: https://sysf.one/

ingress:
  enabled: "true"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/default-backend: fallback-backend
  hosts:
    - sysf.one
    - "*.sysf.one"

phpfpm:
  extraVolumeMounts:
    - name: cluster-cache
      mountPath: /mnt/cluster-cache
  resources:
    limits: {}
    requests:
      cpu: 500m
      memory: 1024Mi

extraVolumes:
  - name: sysf-one-tls
    secret:
      secretName: sysf.one-tls
  - name: bryanjiencke-com-tls
    secret:
      secretName: bryanjiencke.com-tls
  - name: stevenjiencke-com-tls
    secret:
      secretName: stevenjiencke.com-tls
  - name: systemf-one-tls
    secret:
      secretName: systemf.one-tls
  - name: theentityframework-com-tls
    secret:
      secretName: theentityframework.com-tls
  - name: cluster-cache
    persistentVolumeClaim:
      claimName: cluster-cache-cluster-storage-connector
      readOnly: "false"

nginx:
  extraVolumeMounts:
    - mountPath: "/etc/letsencrypt/sysf.one"
      name: sysf-one-tls
      readOnly: "true"
    - mountPath: "/etc/letsencrypt/bryanjiencke.com"
      name: bryanjiencke-com-tls
      readOnly: "true"
    - mountPath: "/etc/letsencrypt/stevenjiencke.com"
      name: stevenjiencke-com-tls
      readOnly: "true"
    - mountPath: "/etc/letsencrypt/systemf.one"
      name: systemf-one-tls
      readOnly: "true"
    - mountPath: "/etc/letsencrypt/theentityframework.com"
      name: theentityframework-com-tls
      readOnly: "true"
  resources:
    limits: {}
    requests:
      cpu: 100m
      memory: 256Mi

autoscaling:
  enabled: "true"
  minReplicas: 5
  maxReplicas: 10
  targetCPU: 90
