sys:
  context: cloud
  subcontext: prd
  uri: https://sysf.one/

ingress:
  enabled: true
  hosts:
    - sysf.one
    - systemf.one
    - bryanjiencke.com
    - stevenjiencke.com
    - theentityframework.com
    - bostondrupal.com

phpfpm:
  resources:
    limits: {}
    requests:
      cpu: 500m
      memory: 1024Mi

nginx:
  resources:
    limits: {}
    requests:
      cpu: 100m
      memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 90
