sys:
  context: cid
  subcontext: cid1

persistence:
  enabled: false

autoscaling:
  minReplicas: 1
  maxReplicas: 1

replicas: 1

extraVolumes:
  - name: sysf-one-tls
    secret:
      secretName: sysf.one-tls
  - name: bryanjiencke-com-tls
    secret:
      secretName: bryanjiencke.com-tls
  - name: stevenjiencke-com-tls
    secret:
      secretName: stevenjiencke.com-tls
  - name: systemf-one-tls
    secret:
      secretName: systemf.one-tls
  - name: theentityframework-com-tls
    secret:
      secretName: theentityframework.com-tls
  - name: cid-build-dir
    hostPath:
      path: /builds/drupal/instance/sysf


phpfpm:
  extraVolumeMounts:
    - mountPath: /app
      name: cid-build-dir

nginx:
  extraVolumeMounts:
    - mountPath: "/etc/letsencrypt/sysf.one"
      name: sysf-one-tls
      readOnly: true
    - mountPath: "/etc/letsencrypt/bryanjiencke.com"
      name: bryanjiencke-com-tls
      readOnly: true
    - mountPath: "/etc/letsencrypt/stevenjiencke.com"
      name: stevenjiencke-com-tls
      readOnly: true
    - mountPath: "/etc/letsencrypt/systemf.one"
      name: systemf-one-tls
      readOnly: true
    - mountPath: "/etc/letsencrypt/theentityframework.com"
      name: theentityframework-com-tls
      readOnly: true
    - mountPath: /app
      name: cid-build-dir
